#############################################################################
# Makefile for building: Transmissions
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  TransmissionsQt.pro
# Template: app
# Command: C:\Qt\Static\5.10.0\bin\qmake.exe -o Makefile TransmissionsQt.pro -spec win32-g++ "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\Static\5.10.0\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Static\5.10.0\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Static\5.10.0\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: TransmissionsQt.pro ../../Static/5.10.0/mkspecs/win32-g++/qmake.conf ../../Static/5.10.0/mkspecs/features/spec_pre.prf \
		../../Static/5.10.0/mkspecs/qdevice.pri \
		../../Static/5.10.0/mkspecs/features/device_config.prf \
		../../Static/5.10.0/mkspecs/common/g++-base.conf \
		../../Static/5.10.0/mkspecs/common/angle.conf \
		../../Static/5.10.0/mkspecs/common/windows-vulkan.conf \
		../../Static/5.10.0/mkspecs/common/sanitize.conf \
		../../Static/5.10.0/mkspecs/common/gcc-base.conf \
		../../Static/5.10.0/mkspecs/qconfig.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3danimation.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dcore.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dextras.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dinput.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquick.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3drender.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axbase.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axserver.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_charts.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_charts_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_concurrent.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_core.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_core_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_dbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_gamepad.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_gui.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_gui_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_help.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_help_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_location.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_location_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_multimedia.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_network.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_network_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_networkauth.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_nfc.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_opengl.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_positioning.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_printsupport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_purchasing.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qml.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qml_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qmltest.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quick.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quick_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_repparser.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_script.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_script_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_scripttools.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_scxml.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_sensors.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_serialbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_serialport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_sql.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_sql_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_svg.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_svg_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_testlib.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_uitools.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_webchannel.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_websockets.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_widgets.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_winextras.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_xml.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_xml_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_dsengine.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qgif.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qicns.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qico.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtga.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qwindows.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_scene2d.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../Static/5.10.0/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		../../Static/5.10.0/mkspecs/features/qt_functions.prf \
		../../Static/5.10.0/mkspecs/features/qt_config.prf \
		../../Static/5.10.0/mkspecs/win32-g++/qmake.conf \
		../../Static/5.10.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Static/5.10.0/mkspecs/features/exclusive_builds.prf \
		../../Static/5.10.0/mkspecs/features/toolchain.prf \
		../../Static/5.10.0/mkspecs/features/default_pre.prf \
		../../Static/5.10.0/mkspecs/features/win32/default_pre.prf \
		../../Static/5.10.0/mkspecs/features/resolve_config.prf \
		../../Static/5.10.0/mkspecs/features/exclusive_builds_post.prf \
		../../Static/5.10.0/mkspecs/features/default_post.prf \
		../../Static/5.10.0/mkspecs/features/qml_debug.prf \
		../../Static/5.10.0/mkspecs/features/precompile_header.prf \
		../../Static/5.10.0/mkspecs/features/warn_on.prf \
		../../Static/5.10.0/mkspecs/features/qt.prf \
		../../Static/5.10.0/mkspecs/features/resources.prf \
		../../Static/5.10.0/mkspecs/features/moc.prf \
		../../Static/5.10.0/mkspecs/features/win32/opengl.prf \
		../../Static/5.10.0/mkspecs/features/uic.prf \
		../../Static/5.10.0/mkspecs/features/qmake_use.prf \
		../../Static/5.10.0/mkspecs/features/file_copies.prf \
		../../Static/5.10.0/mkspecs/features/win32/windows.prf \
		../../Static/5.10.0/mkspecs/features/testcase_targets.prf \
		../../Static/5.10.0/mkspecs/features/exceptions.prf \
		../../Static/5.10.0/mkspecs/features/yacc.prf \
		../../Static/5.10.0/mkspecs/features/lex.prf \
		TransmissionsQt.pro \
		../../Static/5.10.0/lib/qtmaind.prl \
		../../Static/5.10.0/plugins/printsupport/windowsprintersupport.prl \
		../../Static/5.10.0/plugins/styles/qwindowsvistastyle.prl \
		../../Static/5.10.0/plugins/platforms/qwindows.prl \
		../../Static/5.10.0/plugins/imageformats/qgif.prl \
		../../Static/5.10.0/plugins/imageformats/qicns.prl \
		../../Static/5.10.0/plugins/imageformats/qico.prl \
		../../Static/5.10.0/plugins/imageformats/qjpeg.prl \
		../../Static/5.10.0/plugins/imageformats/qtga.prl \
		../../Static/5.10.0/plugins/imageformats/qtiff.prl \
		../../Static/5.10.0/plugins/imageformats/qwbmp.prl \
		../../Static/5.10.0/plugins/imageformats/qwebp.prl \
		../../Static/5.10.0/lib/Qt5PrintSupport.prl \
		../../Static/5.10.0/lib/Qt5Widgets.prl \
		../../Static/5.10.0/lib/Qt5Gui.prl \
		../../Static/5.10.0/lib/Qt5Xml.prl \
		../../Static/5.10.0/lib/Qt5Core.prl
	$(QMAKE) -o Makefile TransmissionsQt.pro -spec win32-g++ "CONFIG+=qml_debug"
../../Static/5.10.0/mkspecs/features/spec_pre.prf:
../../Static/5.10.0/mkspecs/qdevice.pri:
../../Static/5.10.0/mkspecs/features/device_config.prf:
../../Static/5.10.0/mkspecs/common/g++-base.conf:
../../Static/5.10.0/mkspecs/common/angle.conf:
../../Static/5.10.0/mkspecs/common/windows-vulkan.conf:
../../Static/5.10.0/mkspecs/common/sanitize.conf:
../../Static/5.10.0/mkspecs/common/gcc-base.conf:
../../Static/5.10.0/mkspecs/qconfig.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3danimation.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dcore.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dextras.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dinput.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dlogic.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquick.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3drender.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_3drender_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axbase.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axbase_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axcontainer.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axserver.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_axserver_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_bluetooth.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_charts.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_charts_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_concurrent.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_core.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_core_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_datavisualization.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_dbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_dbus_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_gamepad.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_gui.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_gui_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_help.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_help_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_location.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_location_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_multimedia.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_network.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_network_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_networkauth.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_nfc.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_nfc_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_opengl.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_opengl_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_openglextensions.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_positioning.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_positioning_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_printsupport.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_purchasing.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qml.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qml_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qmltest.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quick.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quick_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_repparser.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_repparser_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_script.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_script_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_scripttools.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_scxml.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_scxml_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_sensors.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_sensors_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_serialbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_serialport.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_serialport_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_sql.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_sql_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_svg.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_svg_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_testlib.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_testlib_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_texttospeech.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_uiplugin.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_uitools.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_uitools_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_webchannel.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_websockets.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_websockets_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_widgets.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_widgets_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_winextras.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_winextras_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_xml.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_xml_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_lib_zlib_private.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_dsengine.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qgif.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qicns.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qico.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qminimal.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qsvg.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtga.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtiff.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qwebgl.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qwebp.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qwindows.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_scene2d.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../Static/5.10.0/mkspecs/modules/qt_plugin_xinputgamepad.pri:
../../Static/5.10.0/mkspecs/features/qt_functions.prf:
../../Static/5.10.0/mkspecs/features/qt_config.prf:
../../Static/5.10.0/mkspecs/win32-g++/qmake.conf:
../../Static/5.10.0/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Static/5.10.0/mkspecs/features/exclusive_builds.prf:
../../Static/5.10.0/mkspecs/features/toolchain.prf:
../../Static/5.10.0/mkspecs/features/default_pre.prf:
../../Static/5.10.0/mkspecs/features/win32/default_pre.prf:
../../Static/5.10.0/mkspecs/features/resolve_config.prf:
../../Static/5.10.0/mkspecs/features/exclusive_builds_post.prf:
../../Static/5.10.0/mkspecs/features/default_post.prf:
../../Static/5.10.0/mkspecs/features/qml_debug.prf:
../../Static/5.10.0/mkspecs/features/precompile_header.prf:
../../Static/5.10.0/mkspecs/features/warn_on.prf:
../../Static/5.10.0/mkspecs/features/qt.prf:
../../Static/5.10.0/mkspecs/features/resources.prf:
../../Static/5.10.0/mkspecs/features/moc.prf:
../../Static/5.10.0/mkspecs/features/win32/opengl.prf:
../../Static/5.10.0/mkspecs/features/uic.prf:
../../Static/5.10.0/mkspecs/features/qmake_use.prf:
../../Static/5.10.0/mkspecs/features/file_copies.prf:
../../Static/5.10.0/mkspecs/features/win32/windows.prf:
../../Static/5.10.0/mkspecs/features/testcase_targets.prf:
../../Static/5.10.0/mkspecs/features/exceptions.prf:
../../Static/5.10.0/mkspecs/features/yacc.prf:
../../Static/5.10.0/mkspecs/features/lex.prf:
TransmissionsQt.pro:
../../Static/5.10.0/lib/qtmaind.prl:
../../Static/5.10.0/plugins/printsupport/windowsprintersupport.prl:
../../Static/5.10.0/plugins/styles/qwindowsvistastyle.prl:
../../Static/5.10.0/plugins/platforms/qwindows.prl:
../../Static/5.10.0/plugins/imageformats/qgif.prl:
../../Static/5.10.0/plugins/imageformats/qicns.prl:
../../Static/5.10.0/plugins/imageformats/qico.prl:
../../Static/5.10.0/plugins/imageformats/qjpeg.prl:
../../Static/5.10.0/plugins/imageformats/qtga.prl:
../../Static/5.10.0/plugins/imageformats/qtiff.prl:
../../Static/5.10.0/plugins/imageformats/qwbmp.prl:
../../Static/5.10.0/plugins/imageformats/qwebp.prl:
../../Static/5.10.0/lib/Qt5PrintSupport.prl:
../../Static/5.10.0/lib/Qt5Widgets.prl:
../../Static/5.10.0/lib/Qt5Gui.prl:
../../Static/5.10.0/lib/Qt5Xml.prl:
../../Static/5.10.0/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile TransmissionsQt.pro -spec win32-g++ "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Qt\projets\TransmissionsQt\transmissions_plugin_import.cpp .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
